forum/urls.py
from django.urls import path
from . import views

app_name = 'forum'
urlpatterns = [
    path('', views.home, name="home"),

    # post
    path('post/<int:post_id>', views.postView, name="post"),
    path('post/<int:post_id>/reply', views.newReply, name='reply'),
    path('post/<int:post_id>/lock', views.lockPost, name='lock_post'),
    path('post/<int:post_id>/unlock', views.unlockPost, name='unlock_post'),
    path('post/<int:post_id>/report', views.reportPost, name='report_post'),
    path('post/new', views.createPost, name='create_post'),
    path('post/new/<int:category_id>', views.createPostWCat, name='create_post_cat'),
    path('post/<int:post_id>/delete', views.deletePost, name='delete_post'),
    path('post/<int:post_id>/like', views.likePost, name='like_post'),

    # reply
    path('reply/<int:reply_id>/edit', views.editReply, name='editreply'),
    path('reply/<int:reply_id>/delete', views.deleteReply, name='deletereply'),

    # report
    path('reports/post/<int:post_id>', views.viewPostReports, name='view_post_reports'),
    path('reports/resolve/<int:report_id>', views.resolveReport, name='resolve_report'),

    # category
    path('category/<str:cat_slug>', views.categoryView, name="category"),

    # profile
    path('profile/<int:profile_id>', views.profileView, name='profile'),

    # course
    path('course/<str:course_code>', views.courseView, name='course'),

    # tags
    path('tag/<str:tag_slug>', views.tagView, name="tag"),

    # search
    path('search/', views.searchView, name="search")
]

studydeck_forum/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("users.urls")),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('allauth.socialaccount.urls')),
    path('forum/', include('forum.urls')),
]

forum/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from core.models import Course, Resource

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=20)
    slug = models.SlugField(max_length=20, unique=True)
    desc = models.TextField()

    def __str__(self):
        return self.name
        
class Tag(models.Model):
    name = models.CharField(max_length=20)
    slug = models.SlugField(unique=True, max_length=20, blank=True)

class Reply(models.Model):
    content = models.TextField()
    date_posted = models.DateTimeField(default = timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey('Post', on_delete=models.CASCADE) 
    is_deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f'Reply to post - {self.post}'
    
    def author_id_extracted(self): # using author_id conflicted with django names
        return self.author.email[1:9]

class Post(models.Model):
    title = models.CharField(max_length=100) # max length is required
    content = models.TextField() # max length not required
    date_posted = models.DateTimeField(default = timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name='liked_posts', blank=True)
    is_locked = models.BooleanField(default=False)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, blank=True)

    def __str__(self) -> str:
        return self.title
    
    def get_absolute_url(self):
        return reverse('forum:home') # replace with the post page

    # extract id from email
    def author_id_extracted(self): # using author_id conflicted with django names
        return self.author.email[1:9]
    
class Report(models.Model):
    statuschoice = [
        ("R", "Resolved"),
        ("P", "Pending"),
        ("X", "Rejected"),
    ]

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    reason = models.CharField(max_length=50)
    description = models.TextField()
    status = models.CharField(choices=statuschoice, max_length=15, default="P")
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date_posted = models.DateTimeField(default=timezone.now)
    
    def __str__(self) -> str:
        return f"Report to post - {self.post.title}"
    
    def author_id_extracted(self): # using author_id conflicted with django names
        return self.author.email[1:9]

forum/forms.py
from django import forms
from .models import Post, Reply, Report

class replyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ['content']

class reportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ['reason', 'description']

class postForm(forms.ModelForm):
    tags_input = forms.CharField(
        label="Tags (Separated by commas)",
        required=False,
    )

    class Meta:
        model = Post
        fields = ['title', 'content', 'category', 'course', 'tags_input']

class searchForm(forms.ModelForm):
    class Meta:
        fields = ['post_title']

forum/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.http import HttpResponse
from datetime import datetime
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from .models import Post, Category, Reply, Report, Tag
from core.models import Course, Resource
from .forms import replyForm, reportForm, postForm, searchForm
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.utils.text import slugify
from .helpers import send_reply_notification
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required
from fuzzywuzzy import fuzz, process
import logging
logger = logging.getLogger(__name__)

# Create your views here.
@login_required(login_url='users:home')
def home(request):
    category_list = Category.objects.all()
    total_posts_count = Category.objects.all().count()
    post_list = Post.objects.all().order_by('-date_posted')
    paginator = Paginator(post_list, 5)

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        "category_list": category_list,
        "total_posts_count": total_posts_count,
        "post_list": post_list,
        "page_obj": page_obj,
    }
    return render(request, 'forum/home.html', context=context)

@login_required(login_url='users:home')
def createPostWCat(request, category_id = None):
    initial_data = {}
    if category_id:
        initial_data['category'] = category_id

    if request.method == 'POST':
        form = postForm(request.POST)

        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()

            # for tags
            tag_data = request.POST.get('tags_input', '')
            if tag_data:
                tag_list = [t.strip() for t in tag_data.split(',') if t.strip()]
                for tag_name in tag_list:
                    tag_obj, created = Tag.objects.get_or_create(name=tag_name, defaults={'slug': slugify(tag_name)})
                    post.tags.add(tag_obj)

            return redirect('forum:post', post_id = post.pk)
    else:
        form = postForm(initial=initial_data)

    return render(request, 'forum/create_post.html', {'form': form})

@login_required(login_url='users:home')
def createPost(request):
    if request.method == 'POST':
        form = postForm(request.POST)

        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()

            # for tags
            tag_data = request.POST.get('tags_input', '') # '' is fallback value
            if tag_data:
                tag_list = [t.strip() for t in tag_data.split(',') if t.strip()]
                for tag_name in tag_list:
                    tag_obj, created = Tag.objects.get_or_create(name=tag_name, defaults={'slug': slugify(tag_name)})
                    post.tags.add(tag_obj)

            return redirect('forum:post', post_id = post.pk)
    else:
        form = postForm()

    return render(request, 'forum/create_post.html', {'form': form})

@login_required(login_url='users:home')
def deletePost(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    
    if post.author == request.user or request.user.is_staff or request.user.groups.filter(name='Moderators').count():
        post.delete()

        return redirect('forum:home')
    else:
        # return HttpResponse(f"<h1>You are not allowed here {request.user.username}</h1>")
        raise PermissionDenied
    
@login_required(login_url='users:home')
def likePost(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)
    return redirect('forum:post', post_id=post_id)

@login_required(login_url='users:home') 
def postView(request, post_id):
    post = Post.objects.get(pk = post_id)
    is_mod = request.user.groups.filter(name='Moderators').count()
    report_list = post.report_set.filter(status='P')
    reply_list = post.reply_set.all().order_by('-pk')

    return render(request, 'forum/post.html', context={'post': post, 'is_mod': is_mod, 'report_list': report_list, 'reply_list': reply_list})

@login_required(login_url='users:home')
def newReply(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if post.is_locked:
        raise PermissionDenied
    else:
        if request.method == 'POST':
            form = replyForm(request.POST)

            if form.is_valid():
                reply = form.save(commit=False)
                reply.post = post
                reply.author = request.user
                reply.save()

                if post.author.email and post.author != request.user:
                    send_reply_notification(post, reply)

                return redirect('forum:post', post_id = post.pk)
        else:
            form = replyForm()

        return render(request, 'forum/reply.html', {'form': form, 'post': post})

@login_required(login_url='users:home')
def categoryView(request, cat_slug):
    cat = get_object_or_404(Category, slug=cat_slug)
    post_list = cat.post_set.all().order_by('-pk')
    paginator = Paginator(post_list, 5)

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    return render(request, 'forum/category.html', context={"category": cat, "post_list": post_list, "page_obj": page_obj}) # type: ignore post_set error

@login_required(login_url='users:home')
def editReply(request, reply_id):
    reply = get_object_or_404(Reply, pk=reply_id)

    if request.user == reply.author or request.user.is_staff or request.user.groups.filter(name='Moderators').count():
        if request.method == "POST":
            form = replyForm(request.POST, instance=reply) # instance will prefill the fields
            if form.is_valid():
                form.save()
                return redirect('forum:post', post_id=reply.post.pk)
        else:
            form = replyForm(instance=reply)

        return render(request, 'forum/edit_reply.html', {
            'reply': reply, 'form': form, 'post': reply.post,
        })
    
    else:
        # return HttpResponse("<h1>You are not allowed here </h1>")
        raise PermissionDenied

@login_required(login_url='users:home')   
def deleteReply(request, reply_id):
    reply = get_object_or_404(Reply, id=reply_id)
    post_id = reply.post.pk
    
    if reply.author == request.user or request.user.is_staff or request.user.groups.filter(name='Moderators').count():
        reply.is_deleted = True
        reply.save()

        return redirect('forum:post', post_id=post_id)
    else:
        # return HttpResponse(f"<h1>You are not allowed here f{request.user.username}</h1>")
        raise PermissionDenied

    
@login_required(login_url='users:home')
def profileView(request, profile_id):
    profile_user = get_object_or_404(User, email = f"f{profile_id}@pilani.bits-pilani.ac.in")
    is_mod = profile_user.groups.filter(name='Moderators').count()
    user_posts = profile_user.post_set.all().order_by('-pk') # type: ignore

    paginator = Paginator(user_posts, 5)

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    return render(request, 'forum/profile.html', context= {
        'profile_user': profile_user,
        'user_posts': user_posts,
        'user_post_count': user_posts.count(),
        'reply_count': profile_user.reply_set.count(), # type: ignore
        'is_mod': is_mod,
        'page_obj': page_obj,
    })

@login_required(login_url='users:home')
def reportPost(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.method == "POST":
        form = reportForm(request.POST)

        if form.is_valid():
            report = form.save(commit=False)
            report.post = post
            report.author = request.user
            report.save()
            return redirect('forum:post', post_id = post_id)
    
    else:
        form = reportForm()

    return render(request, 'forum/report_post.html', context={'post': post, 'form': form})

@login_required(login_url='users:home')
def viewPostReports(request, post_id):
    is_mod = request.user.groups.filter(name='Moderators').count()

    if request.user.is_staff or is_mod:
        post = Post.objects.get(pk = post_id)
        report_list = post.report_set.filter(status='P') # type: ignore
        return render(request, 'forum/view_post_reports.html', context={'post': post, 'is_mod': is_mod, 'report_list': report_list})
    
    else:
        # return HttpResponse('<h1>You are not allowed here</h1>')
        raise PermissionDenied

    
@login_required(login_url='users:home')
def resolveReport(request, report_id):
    is_mod = request.user.groups.filter(name='Moderators').count()

    if request.user.is_staff or is_mod:
        report = get_object_or_404(Report, pk=report_id)
        post = report.post
        report.status = 'R'
        report.save()

        return redirect('forum:view_post_reports', post_id = post.pk)
    
    else:
        # return HttpResponse("<h1>You are not allowed here</h1>")
        raise PermissionDenied


@login_required(login_url='users:home')
def lockPost(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.user.is_staff or request.user.groups.filter(name='Moderators').count():
        post.is_locked = True
        post.save()

        return redirect('forum:post', post_id = post_id)
    
    else:
        # return HttpResponse("<h1>You are not allowed here</h1>")
        raise PermissionDenied

@login_required(login_url='users:home')  
def unlockPost(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

forum/templates/forum/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'forum/forum.css' %}">

    <title>StudyDeck Forum</title>
</head>

<body>
    <div class="container">
        {% block content %} {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

forum/templates/forum/create.html
{% extends "forum/base.html" %}

{% block content %}
  <h2>Create a New Post</h2>

  <form method="post">
    {% csrf_token %}
    
    {{ form.as_p }}

    <button type="submit" class="btn btn-primary">Publish Post</button>
  </form>

  <br>
  <a href="{% url 'forum:home' %}">Cancel and go back</a>
{% endblock content %}

forum/templates/forum/post.html
{% extends 'forum/base.html' %}
{% load static %}
{% load markdown_extras %}

{% block content %}
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="wrapper wrapper-content animated fadeInRight">

                <div class="ibox-content m-b-sm border-bottom">
                    <div class="p-xs">
                        <div class="pull-left m-r-md">
                            <a href="/">
                            <img src="{% static 'images/studydeck.png' %}" 
                                alt="studydeck-icon"
                                class="mid-icon" 
                                style="width: 1.5em; height: 1.5em; object-fit: contain; vertical-align: middle; margin-top: -10px;">
                            </a>
                        </div>

                        <div class="pull-right m-r-md"> <!-- just replace pull-left w/ pull-right-->>
                            <a href="{% url 'account_logout' %}" class="btn btn-danger btn-sm" style="margin-top: 20px;">Logout</a>
                        </div>

                        <h2 style="text-align: center;">StudyDeck Forum</h2>

                    <div class="text-center">
                        {% if user.socialaccount_set.all %}
                            <span>Logged in as {{ user.first_name }} {{ user.last_name }}</span>
                        {% elif user.is_staff %}
                            <span>Logged in as ADMIN</span>
                        {% else %}
                            <span>Logged in as {{ user.username }}</span>
                        {% endif %}
                    </div>
                    </div>
                </div>

                <div class="ibox-content m-b-sm border-bottom">
                    <div class="p-xs">
                        {% if user.is_staff or is_mod %}
                            <div class="pull-right">
                                <a href="{% url 'forum:view_post_reports' post.id %}" class="btn btn-warning btn-xs">
                                    <i class="fa fa-flag text-danger"></i> {{ report_list.count}} Reports
                                </a>
                            </div>     
                        {% endif %}
                            <div class="pull-right">
                                <a href="{% url 'forum:like_post' post.id %}" class="btn btn-white btn-xs">
                                    <i class="fa fa-thumbs-up text-info"></i> Like ({{ post.likes.count }})
                                </a>

                                <a href="{% url 'forum:report_post' post.id %}" class="btn btn-white btn-xs">
                                    <i class="fa fa-flag text-danger"></i> Report
                                </a>

                                {% if user == post.author or user.is_staff or is_mod %}
                                    <a href="{% url 'forum:delete_post' post.id %}" 
                                    class="btn btn-danger btn-xs" 
                                    onclick="return confirm('Are you sure you want to delete this post? This cannot be undone.');">
                                        <i class="fa fa-trash"></i> Delete
                                    </a>
                                {% endif %}
                            </div>

                        <div class="pull-left m-r-md">
                            {% if post.author.socialaccount_set.all %}
                                <a href="{% url 'forum:profile' post.author_id_extracted %}">
                                    <img src="{{ post.author.socialaccount_set.all.0.get_avatar_url }}" 
                                        alt="Profile Picture"
                                        class="rounded-circle border"
                                        style="width: 3.5em; height: 3.5em; object-fit: cover;" />
                                </a>
                            {% else %}
                                <i class="fa fa-comments-o text-navy mid-icon" style="font-size: 48px;"></i>
                            {% endif %}
                        </div>

                        <div class="clear">
                            <h2 class="m-b-none">{{ post.title }}</h2>
                            
                            <div class="m-t-xs">
                                <small class="text-muted">
                                    <a class="fa fa-folder-open" href="{% url 'forum:home' %}category/{{ post.category.slug }}"></a> 
                                    <a href="{% url 'forum:home' %}category/{{ post.category.slug }}"><strong >{{ post.category.name }}</strong></a> 
                                    &nbsp;&nbsp;
                                    {% if post.course %}
                                        <a class="fa fa-mortar-board" href="{% url 'forum:course' post.course.code %}"></a> 
                                        <a href="{% url 'forum:course' post.course.code %}"><strong>{{ post.course.name }}</strong></a>
                                        &nbsp;&nbsp;
                                    {% endif %}
                                    <i class="fa fa-user"></i> {{ post.author.first_name }} {{ post.author.last_name }}
                                    <i class="fa fa-clock-o"></i> Posted on {{ post.date_posted|date }} at {{ post.date_posted|time }}
                                </small>
                            </div>

                            <!-- for showing tags -->
                            {% if post.tags.all %}
                            <div class="m-t-xs m-b-sm">
                                {% for tag in post.tags.all %}
                                    <a href="{% url 'forum:tag' tag.slug %}" class="btn btn-white btn-xs" style="border-radius: 10px; margin-right: 5px;">
                                        <i class="fa fa-tag text-info"></i> {{ tag.name }}
                                    </a>
                                {% endfor %}
                            </div>
                            {% endif %}
                            
                            <br>
                            <div class="m-t-sm">
                                <p style="font-size: 1.1em; line-height: 1.5;">{{ post.content | markdown | safe }}</p> 
                                <!--doesnt print without safe because safe tells python its safe to render-->
                            </div>
                        </div>
                    </div>
                </div>

                <div class="ibox-content forum-container">
                    
                    <div class="forum-title">
                        {% if post.is_locked %}
                            <div class="pull-right">
                                <strong>This post is locked</strong><br>
                                <strong>No more replies can be added</strong>
                            </div>
                        {% else %}
                            <div class="pull-right">
                                <a href="{% url 'forum:reply' post.id %}" class="btn btn-primary btn-sm">
                                    <i class="fa fa-plus"></i> Add Reply
                                </a>
                            </div>
                        {% endif %}
                        <h3>Replies</h3>
                    </div>

                    {% for reply in reply_list %}
                        {% if reply.is_deleted %}
                            <div class="forum-item">
                                <div class="row">
                                    <div class="col-md-9">
                                        <div class="forum-icon">
                                                <img src="{% static 'images/deleted_icon.png' %}" 
                                                    alt="Profile Picture"
                                                    class="rounded-circle border"
                                                    style="width: 3em; height: 3em;" />
                                        </div>
                                            <span class="forum-item-title"><strong>Deleted</strong></span>


                                        <div class="forum-sub-title">This reply has been deleted</div>

                                    </div>
                                    
                                    <div class="col-md-3 forum-info">
                                        <small>Posted on {{ reply.date_posted|date }} at {{ reply.date_posted|time }}</small>
                                    </div>
                                </div>
                            </div>

                        {% else %}
                            <div class="forum-item">
                                <div class="row">
                                    <div class="col-md-9">
                                        <div class="forum-icon">
                                            {% if reply.author.socialaccount_set.all %}
                                                <a href="{% url 'forum:profile' reply.author_id_extracted %}">
                                                    <img src="{{ reply.author.socialaccount_set.all.0.get_avatar_url }}" 
                                                        alt="Profile Picture"
                                                        class="rounded-circle border"
                                                        style="width: 3em; height: 3em;" />
                                                </a>
                                            {% else %}
                                                <img src="{% static 'images/studydeck.png' %}" 
                                                    alt="Profile Picture"
                                                    class="rounded-circle border"
                                                    style="width: 3em; height: 3em;" />
                                            {% endif %}
                                        </div>

                                        {% if reply.author.socialaccount_set.all %}
                                            <a href="#" class="forum-item-title">{{ reply.author.first_name }} {{ reply.author.last_name }}</a>
                                        {% elif reply.author.is_staff %}
                                            <span class="forum-item-title"><strong>ADMIN</strong></span>
                                        {% else %}
                                            <span class="forum-item-title"><strong>{{ reply.author.username }}</strong></span>
                                        {% endif %}

                                        <div class="forum-sub-title">{{ reply.content | markdown | safe }}</div>

                                        {% if user.is_authenticated %}
                                            {% if user == reply.author or user.is_staff or is_mod %}
                                                <div class="m-t-xs">
                                                    <a href="{% url 'forum:editreply' reply.id %}" class="text-navy small">
                                                        <i class="fa fa-edit"></i> Edit
                                                    </a>
                                                </div>
                                            {% endif %}
                                        {% endif %}
                                    </div>
                                    
                                    <div class="col-md-3 forum-info">
                                        <small>Posted on {{ reply.date_posted|date }} at {{ reply.date_posted|time }}</small>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% empty %}
                        <div class="forum-item">
                            <div class="row">
                                <div class="col-md-12 text-center p-md">
                                    <span class="text-muted">No replies yet. Be the first to join the conversation!</span>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>

            </div>
        </div>
    </div>
</div>
{% endblock content %}

forum/templates/forum/post_old.html
{% extends 'forum/base.html' %}
{% load static %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p>{{ post.content }}</p>

    <br>
    <br>
    <div class="d-flex justify-content-between align-items-center mt-4 mb-3">
    <h2 class="mb-0"> Replies </h2>
        <a href="{% url 'forum:reply' post.id %}" class="btn btn-primary">
            <i class="bi bi-plus-lg"></i> Add Reply
        </a>
    </div>

    {% for reply in post.reply_set.all %}
        <div class="forum-item">
            <div class="row">
                <div class="col-md-9">
                    <div class="forum-icon">
                        {% if reply.author.socialaccount_set.all %}
                            <a href="/profile/{{ post.author_id_extracted }}">
                            <img src="{{ reply.author.socialaccount_set.all.0.get_avatar_url }}" 
                                alt="Profile Picture"
                                class="rounded-circle border"
                                style="width: 3em; height: 3em;" />
                            </a>
                        {% else %}
                            <img src="{% static 'images/studydeck.png' %}" 
                                alt="Profile Picture"
                                class="rounded-circle border"
                                style="width: 3em; height: 3em;" />
                            </a>
                        {% endif %}
                    </div>

                    {% if reply.author.socialaccount_set.all %}
                        <a href="{{ post.id }}" class="forum-item-title">{{ reply.author.first_name }} {{ reply.author.last_name }} </a>
                    {% else %}
                        <a class="forum-item-title"><b><u>ADMIN</u></b></p>
                    {% endif %}

                    <div class="forum-sub-title">{{ reply.content }}</div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock content %}